apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-os-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-os-api
  template:
    metadata:
      labels:
        app: customer-os-api
    spec:
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os/customer-os-api:latest
          name: customer-os-api
          imagePullPolicy: Never
          ports:
            - containerPort: 10000
          livenessProbe:
            httpGet:
              path: /health
              port: 10000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 10000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: NEO4J_TARGET
              value: "neo4j://customer-db-neo4j.openline.svc.cluster.local:7687"
            - name: NEO4J_AUTH_USER
              value: "neo4j"
            - name: NEO4J_AUTH_PWD
              value: "StrongLocalPa$$$"
            - name: NEO4J_AUTH_REALM
              value: ""
            - name: NEO4J_MAX_CONN_POOL_SIZE
              value: "100"
            - name: NEO4J_LOG_LEVEL
              value: "INFO"

            - name: POSTGRES_USER
              value: "openline"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "openline"
            - name: POSTGRES_HOST
              value: "customer-db-postgresql.openline.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_MAX_CONN
              value: "25"
            - name: POSTGRES_MAX_IDLE_CONN
              value: "10"
            - name: POSTGRES_CONN_MAX_LIFETIME
              value: "0"
            - name: POSTGRES_LOG_LEVEL
              value: "WARN"

            - name: PORT
              value: "10000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: GRAPHQL_PLAYGROUND_ENABLED
              value: "true"
            - name: GRAPHQL_FIXED_COMPLEXITY_LIMIT
              value: "1000"

            - name: EVENTS_PROCESSING_PLATFORM_URL
              value: "events-processing-platform-service.openline.svc.cluster.local:5001"
            - name: EVENTS_PROCESSING_PLATFORM_API_KEY
              value: "082c1193-a5a2-42fc-87fc-e960e692fffd"

            - name: JAEGER_AGENT_HOST
              value: "jaeger.openline.svc.cluster.local"
            - name: JAEGER_AGENT_PORT
              value: "6831"

