apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-processing-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-processing-platform
  template:
    metadata:
      labels:
        app: events-processing-platform
    spec:
      containers:
        - image: ghcr.io/openline-ai/openline-customer-os/events-processing-platform:latest
          name: events-processing-platform
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001  # Should match the port number that the Go application listens on
              name: grpc-port
          env:
            - name: SERVICE_NAME
              value: "events-processing-platform"

            - name: EVENT_STORE_CONNECTION_STRING
              value: "esdb://event-store-service.openline.svc.cluster.local:2113"
            - name: EVENT_STORE_CONNECTION_TLS_DISABLED
              value: "true"
            - name: EVENT_STORE_CONNECTION_TLS_VERIFY_CERT
              value: "false"
            - name: EVENT_STORE_CONNECTION_KEEP_ALIVE_TIMEOUT
              value: "10000"
            - name: EVENT_STORE_CONNECTION_KEEP_ALIVE_INTERVAL
              value: "10000"

            - name: EVENT_STORE_SUBSCRIPTIONS_GRAPH_ENABLED
              value: "true"
            - name: EVENT_STORE_SUBSCRIPTIONS_GRAPH_POOL_SIZE
              value: "4"

            - name: EVENT_STORE_SUBSCRIPTIONS_EMAIL_VALIDATION_ENABLED
              value: "true"
            - name: EVENT_STORE_SUBSCRIPTIONS_EMAIL_VALIDATION_POOL_SIZE
              value: "1"

            - name: GRPC_PORT
              value: ":5001"
            - name: GRPC_DEVELOPMENT
              value: "true"
            - name: GRPC_API_KEY 
              value: "082c1193-a5a2-42fc-87fc-e960e692fffd"

            - name: LOGGER_LEVEL
              value: "debug"
            - name: LOGGER_DEV_MODE
              value: "false"
            - name: LOGGER_ENCODER
              value: "console"

            - name: JAEGER_ENABLE
              value: "true"
            - name: JAEGER_SERVICE_NAME
              value: "event-processing-platform"
            - name: JAEGER_HOST_PORT
              value: "localhost:6831"
            - name: JAEGER_LOG_SPANS
              value: "false"

            - name: NEO4J_TARGET
              value: "neo4j://customer-db-neo4j.openline.svc.cluster.local:7687"
            - name: NEO4J_AUTH_USER
              value: "neo4j"
            - name: NEO4J_AUTH_PWD
              value: "StrongLocalPa$$"
            - name: NEO4J_AUTH_REALM
              value: ""
            - name: NEO4J_MAX_CONN_POOL_SIZE
              value: "100"
            - name: NEO4J_CONN_ACQUISITION_TIMEOUT_SEC
              value: "60"
# valid log values (ERROR, WARNING, INFO, DEBUG)
            - name: NEO4J_LOG_LEVEL
              value: "INFO"

            - name: VALIDATION_API
              value: "http://validation-api-service.openline.svc.cluster.local:10003"
            - name: VALIDATION_API_KEY
              value: "d02520f5-7705-4b73-9510-a7c9507e695e"

            - name: JAEGER_AGENT_HOST
              value: "jaeger.openline.svc.cluster.local"
            - name: JAEGER_AGENT_PORT
              value: "6831"

            - name: POSTGRES_HOST
              value: "customer-db-postgresql.openline.svc.cluster.local"