# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "password"
  username: "openline"
  password: "password"
  database: "openline"

# The postgresql helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "customer-db-postgresql-claim"
  service:
    type: LoadBalancer

volumePermissions:
  enabled: true