name: customer-os-api

on:
  push:
    branches: [ "otter" ]
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/events-processing-common/**
      - packages/server/customer-os-api/**
      - .github/workflows/build-customer-os-api.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/events-processing-common/**
      - packages/server/customer-os-api/**
      - .github/workflows/build-customer-os-api.yml
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/customer-os-api

permissions:
  contents: read
  pull-requests: read
  packages: write

defaults:
  run:
    working-directory: ./packages/server/customer-os-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Build
        run: make all

      - name: Test
        run: gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...

      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()    # run this step even if previous step failed
        with:
          report_paths: ./packages/server/customer-os-api/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY

  build-publish:
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare sources for docker build
        run: |
          mkdir tmp-sources
          mkdir tmp-sources/customer-os-common-module
          mkdir tmp-sources/customer-os-api
          mkdir tmp-sources/events-processing-common
          
          rsync -av --progress --exclude="tmp-sources" * tmp-sources/customer-os-api
          cp .env tmp-sources/customer-os-api/.env
          cp -r ../customer-os-common-module/* tmp-sources/customer-os-common-module
          cp -r ../events-processing-common/* tmp-sources/events-processing-common
          
          cp Dockerfile tmp-sources/Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: packages/server/customer-os-api/tmp-sources/.
          push: ${{ github.ref_name == 'otter' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}