name: file-store-api

on:
  push:
    branches: [ "otter" ]
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/file-store-api/**
      - .github/workflows/build-filestore-api.yml
  pull_request:
    paths:
      - packages/server/customer-os-common-module/**
      - packages/server/file-store-api/**
      - .github/workflows/build-filestore-api.yml
  release:
    types: [ created, edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/file-store-api

permissions:
  contents: read
  pull-requests: read
  packages: write

defaults:
  run:
    working-directory: ./packages/server/file-store-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Build
        run: make all

      - name: Configure Test Folders
        id: test-folders
        run: |
          test_folders=$(go list ./... | grep -v /gen | grep -v /test | paste -sd "," -)
          echo "::set-output name=test_folders::$test_folders"

      - name: Test
        run: gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out -coverpkg=${{ steps.test-folders.outputs.test_folders }} ./...

      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()    # run this step even if previous step failed
        with:
          report_paths: ./packages/server/file-store-api/unit-tests.xml    # Path to test results
          include_passed: true
          annotate_only: true
          detailed_summary: true

      - name: Compute Code Coverage
        id: compute_code_coverage
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY

  build-publish:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare sources for docker build
        run: |
          mkdir tmp-sources
          mkdir tmp-sources/customer-os-common-module
          mkdir tmp-sources/file-store-api
          
          rsync -av --progress --exclude="tmp-sources" * tmp-sources/file-store-api
          cp .env tmp-sources/file-store-api/.env
          cp -r ../customer-os-common-module/* tmp-sources/customer-os-common-module
          
          cp Dockerfile tmp-sources/Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
          password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: packages/server/file-store-api/tmp-sources/.
          push: ${{ github.ref_name == 'otter' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}